### ISSUE TITLE
Internal error

### ISSUE THREAD

**Issue by wangshengshun** [DefaultValue/redmine-project-state#1]
Internal error
An error occurred on the page you were trying to access.
If you continue to experience problems please contact your Redmine administrator for assistance.

If you are the Redmine administrator, check your log files for details about the error.

I use redmine3.4.2.stable version here, after installing the plug-in, the above error occurs, you can look over there? Thank you!
In the plug-in configuration page, click the "Apply" button, the above error occurs

**Comment by nowiko** [comment]
Hello @wangshengshun 
Thanks for feedback.
Could you please provide us with Redmine error logs?
You are able to find logs by following path `path/to/your/redmine/log/production.log`. 
Please attach here latest records from the log file, after you got error page.

Best regards.

**Comment by wangshengshun** [comment]
Log file has been sent to your mailbox, you have a look what the problem is now just use the plug-in, thank you！

**Comment by nowiko** [comment]
@wangshengshun 
Please insert log file here or into the gist. We did not receive anything.

**Comment by wangshengshun** [comment]
@nowiko 
Hello! Here is my error log message：
Started GET "/redmine/settings/plugin/project_state" for 112.224.67.175 at 2018-03-08 21:14:53 +0800
Processing by SettingsController#plugin as HTML
  Parameters: {"id"=>"project_state"}
  Current user: admin (id=1)
  Rendered plugins/project_state/app/views/settings/_project_state_settings.html.erb (6.0ms)
  Rendered settings/plugin.html.erb within layouts/admin (7.5ms)
  Rendered admin/_menu.html.erb (8.0ms)
  Rendered plugins/quick_view/app/views/hooks/_quick_view_base_head.html.erb (0.0ms)
  Rendered plugins/redmine_code_review/app/views/code_review/_html_header.html.erb (0.0ms)
  Rendered plugins/clipboard_image_paste/app/views/clipboard_image_paste/_headers.html.erb (1.0ms)
  Rendered plugins/progressive_projects_list/app/views/application/_progressive_sidebar.html.erb (0.0ms)
  Rendered plugins/progressive_projects_list/app/views/application/_progressive_recent_projects.html.erb (0.0ms)
  Rendered plugins/redmine_banner/app/views/banner/_project_body_bottom.html.erb (0.0ms)
  Rendered plugins/sidebar_hide/app/views/sidebar/_hideButton_partial.html.erb (0.0ms)
  Rendered plugins/quick_view/app/views/hooks/_quick_view_base_bottom_tooltip.html.erb (1.5ms)
  Rendered plugins/quick_view/app/views/hooks/_quick_view_base_bottom.html.erb (2.0ms)
  Rendered plugins/quick_view/app/views/hooks/_quick_view_base_bottom_worktime_ext.html.erb (1.5ms)
  Rendered plugins/redmine_code_review/app/views/code_review/_body_bottom.html.erb (0.0ms)
  Rendered plugins/clipboard_image_paste/app/views/clipboard_image_paste/_add_form.html.erb (5.5ms)
  Rendered layouts/base.html.erb (80.5ms)
Completed 200 OK in 137ms (Views: 86.9ms | ActiveRecord: 43.5ms)
Started POST "/redmine/settings/plugin/project_state" for 112.224.67.175 at 2018-03-08 21:15:35 +0800
Processing by SettingsController#plugin as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"OWteCY0REXl1xmOYTrZ6rYoO00xLLbFTE0JALjxdsRueNEcxW3VH7vwjaUPD4+UJH+cZf/ExxI8GD9l36kyHVQ==", "settings"=>["", "", "", "", "", "", "", "", "", "", "", ""], "commit"=>"应用", "id"=>"project_state"}
  Current user: admin (id=1)
Completed 500 Internal Server Error in 35ms (ActiveRecord: 24.0ms)

NoMethodError (undefined method `permit!' for ["", "", "", "", "", "", "", "", "", "", "", ""]:Array
Did you mean?  permutation):
  app/controllers/settings_controller.rb:70:in `plugin'
  plugins/redmine_banner/lib/banner_settings_controller_patch.rb:21:in `plugin_with_banner_date_validation'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'

**Comment by alexandrzhulev** [comment]
Hello @wangshengshun
We have rechecked the issue with purely installed redmine3.4.2.stable version and 'redmine_banner' plugin.
Everything works as expected - plugin settings are saved after 'Apply' is clicked.
As we see settings parameters are overwritten (maybe by some plugin) and 'settings_controller' is trying to process not Paramters object, but the array ["", "", "", "", "", "", "", "", "", "", "", ""].
Could you recheck the issue without any other plugins and let us know the results ?

**Comment by nowiko** [comment]
Hello @wangshengshun 
As there is lack of feedback from you and we haven't reproduced this issue on any local installation of plugin I mark this issue as closed. Feel free to reopen it with expanded description for it.
